// pipeline {
//     agent any
//     options {
//         skipStagesAfterUnstable()
//     }
//     stages {
//         stage('Build') {
//             steps {
//                 sh 'mvn -B -DskipTests clean package'
//             }
//         }
//         stage('Test') {
//             steps {
//                 sh 'mvn test'
//             }
//             post {
//                 always {
//                     junit 'target/surefire-reports/*.xml'
//                 }
//             }
//         }
//         stage('Deliver') { 
//             steps {
//                 sh './jenkins/scripts/deliver.sh' 
//             }
//         }
//     }
// }

pipeline{

    agent any

    tools {
        maven 'test-may15'
    }
    stages{

        stage('build'){
            steps{
                // echo "Build Stage"
                sh 'mvn clean package'
            }

            post {
                success {
                    archiveArtifacts artifacts: '**/target/*.jar'
                }
            }
        }

        // stage('test'){
        //     steps{
        //         // echo "Test Stage"
        //         sh 'mvn'
        //     }
        // }

        // stage('deploy'){
        //     steps{
        //         echo "Deploy Stage"
        //     }
        // }

    }
}
